
export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS";
export const REQUEST_SIGNUP_ERROR = "REQUEST_SIGNUP_ERROR";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_ERROR = "REQUEST_LOGIN_ERROR";

export const POLL_REQUEST = "POLL_REQUEST";
export const POLL_REQUEST_SUCCESS = "POLL_REQUEST_SUCCESS";
export const POLL_REQUEST_ERROR = "POLL_REQUEST_ERROR";


