
export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS";
export const REQUEST_SIGNUP_ERROR = "REQUEST_SIGNUP_ERROR";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_ERROR = "REQUEST_LOGIN_ERROR";

export const POLL_REQUEST = "POLL_REQUEST";
export const POLL_REQUEST_SUCCESS = "POLL_REQUEST_SUCCESS";
export const POLL_REQUEST_ERROR = "POLL_REQUEST_ERROR";

 
export const DELETE_POLL_REQUEST="DELETE_POLL_REQUEST";
export const DELETE_POLL_REQUEST_SUCCESS="DELETE_POLL_REQUEST_SUCCESS";
export const DELETE_POLL_REQUEST_ERROR = "DELETE_POLL_REQUEST_ERROR";

export const EDIT_TITLE_REQUEST = "EDIT_TITLE_REQUEST";
export const EDIT_TITLE_REQUEST_SUCCESS = "EDIT_TITLE_REQUEST_SUCCESS";
export const EDIT_TITLE_REQUEST_ERROR = "EDIT_TITLE_REQUEST_ERROR";

export const NEW_OPTION_REQUEST = "NEW_OPTION_REQUEST";
export const NEW_OPTION_REQUEST_SUCCESS = "NEW_OPTION_REQUEST_SUCCESS";
export const NEW_OPTION_REQUEST_ERROR = "NEW_OPTION_REQUEST_ERROR";

export const REMOVE_OPTION_REQUEST = "REMOVE_OPTION_REQUEST";
export const REMOVE_OPTION_REQUEST_SUCCESS = "REMOVE_OPTION_REQUEST_SUCCESS";
export const REMOVE_OPTION_REQUEST_ERROR = "REMOVE_OPTION_REQUEST_ERROR";


export const ADD_POLL_REQUEST = "ADD_POLL_REQUEST";
export const ADD_POLL_REQUEST_SUCCESS = "ADD_POLL_REQUEST_SUCCESS";
export const ADD_POLL_REQUEST_ERROR = "ADD_POLL_REQUEST_ERROR";


export const VOTE_POLL_REQUEST = "VOTE_POLL_REQUEST";
export const VOTE_POLL_REQUEST_SUCCESS = "VOTE_POLL_REQUEST_SUCCESS";
export const VOTE_POLL_REQUEST_ERROR = "VOTE_POLL_REQUEST_ERROR";



